# Generated by Django 5.2.1 on 2025-05-19 17:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydatek_nazwa', models.CharField(max_length=200)),
                ('wydatek_koszt', models.FloatField()),
                ('wydatek_rodzaj', models.CharField(max_length=100)),
                ('wydatek_data', models.DateTimeField(default=datetime.datetime(2025, 5, 19, 17, 46, 13, 188151, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
