# Generated by Django 5.2.1 on 2025-05-23 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('oplaty_stale', 'Opłaty stałe'), ('jedzenie', 'Jedzenie'), ('przyjemnosci', 'Przyjemności'), ('rozwoj', 'Rozwój'), ('inwestycje', 'Inwestycje'), ('inne', 'Inne')], max_length=30, unique=True)),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydatek_nazwa', models.CharField(default='', max_length=200, verbose_name='Nazwa wydatku')),
                ('wydatek_kwota', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota wydatku')),
                ('wydatek_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wydatku')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wydatek_rodzaj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wydatki.kategoria', verbose_name='Kategoria wydatku')),
            ],
        ),
    ]
