# Generated by Django 5.2.1 on 2025-05-21 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydatek',
            name='wydatek_koszt',
        ),
        migrations.AddField(
            model_name='wydatek',
            name='wydatek_kwota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kwota wydatku'),
        ),
        migrations.AlterField(
            model_name='wydatek',
            name='wydatek_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data wydatku'),
        ),
        migrations.AlterField(
            model_name='wydatek',
            name='wydatek_nazwa',
            field=models.CharField(default='', max_length=200, verbose_name='Nazwa wydatku'),
        ),
        migrations.AlterField(
            model_name='wydatek',
            name='wydatek_rodzaj',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rodzaj wydatku'),
        ),
    ]
