# Generated by Django 5.2.1 on 2025-05-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0002_remove_wydatek_wydatek_koszt_wydatek_wydatek_kwota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
